import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Footer } from "@/components/ui/layout/footer/Footer";
import { Header } from "@/components/ui/layout/header/Header";
import ScrollToTopButton from "@/components/ui/shared/buttons/ScrollToTopButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='ru'>
      <body className={`antialiased`}>
        <Providers>
          <Header />
          <main>
            {children}
            <ScrollToTopButton />
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
