"""Add refresh token for buyer and seller table

Revision ID: e0d19d35add9
Revises: d5e744d3ab31
Create Date: 2025-07-25 15:28:12.209234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0d19d35add9"
down_revision: Union[str, Sequence[str], None] = "d5e744d3ab31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("buyers", sa.Column("refresh_token", sa.String(), nullable=False))
    op.add_column("sellers", sa.Column("refresh_token", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sellers", "refresh_token")
    op.drop_column("buyers", "refresh_token")
    # ### end Alembic commands ###
