"""Add is_active for seller and buyer tables

Revision ID: d5e744d3ab31
Revises: 8ed230e06b8d
Create Date: 2025-07-23 23:31:13.737836

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5e744d3ab31"
down_revision: Union[str, Sequence[str], None] = "8ed230e06b8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("buyers", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("sellers", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sellers", "is_active")
    op.drop_column("buyers", "is_active")
    # ### end Alembic commands ###
