"""Add year characteristics category in Book table

Revision ID: 31bf0e845c65
Revises: 8463754a9e5d
Create Date: 2025-07-19 17:28:34.786284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31bf0e845c65'
down_revision: Union[str, Sequence[str], None] = '8463754a9e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('characteristics', sa.String(), nullable=False))
    op.add_column('books', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'category')
    op.drop_column('books', 'characteristics')
    op.drop_column('books', 'year')
    # ### end Alembic commands ###
