"""Add nullable for refresh token

Revision ID: 59aa39154a6d
Revises: e0d19d35add9
Create Date: 2025-07-26 14:14:27.444223

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59aa39154a6d"
down_revision: Union[str, Sequence[str], None] = "e0d19d35add9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "buyers", "refresh_token", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "sellers", "refresh_token", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sellers", "refresh_token", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "buyers", "refresh_token", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
