"""add book table

Revision ID: d6709b70b0d2
Revises: 59aa39154a6d
Create Date: 2025-08-06 17:18:51.368106

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6709b70b0d2"
down_revision: Union[str, Sequence[str], None] = "59aa39154a6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("characteristics", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("type_book", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("type_cover", sa.String(), nullable=False),
        sa.Column("publishing", sa.String(), nullable=False),
        sa.Column("isbn", sa.String(), nullable=False),
        sa.Column("series", sa.String(), nullable=False),
        sa.Column("seller_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["sellers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "buyers", "refresh_token", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "buyers", "refresh_token", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_table("books")
    # ### end Alembic commands ###
