"""add index for categories

Revision ID: eb8a650d4583
Revises: 9850148bc4d9
Create Date: 2025-08-06 18:40:47.528267

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb8a650d4583"
down_revision: Union[str, Sequence[str], None] = "9850148bc4d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_books_category"), "books", ["category"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_books_category"), table_name="books")
    # ### end Alembic commands ###
